#!/bin/sh
set -eu

dev/fmt
if [ -n "$(git status --untracked-files=no --porcelain)" ]; then
    echo "c_src/re2.cc formatting difference."
    echo "Did you forget to run dev/fmt before git push?"
    git diff
    exit 1
fi
