name: Test
on: [push, pull_request]

jobs:
  dialyzer:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.3
          rebar3-version: 3.17
      - name: Dialyzer
        run: rebar3 dialyzer

  clang-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Print clang-format version
        run: clang-format --version
      - name: Run clang-format 
        run: dev/check-fmt

  test-linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        otp: [24.3]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: 3.17
      - name: Compile
        run: rebar3 compile
      - name: Run tests
        run: rebar3 eunit

  test-linux-debug:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        otp: [24.3]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: 3.17
      - name: Compile
        run: rebar3 as debug compile
      - name: Run tests
        run: rebar3 as debug eunit
      - run: dev/l.sh 128
    env:
      RE2_DEBUG: 1

  # There is an issue with triq which prevents these tests from running ...
  # test-macos:
  #   runs-on: macos-latest
  #   strategy:
  #     matrix:
  #       otp: ["erlang@22", "erlang@23"]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: brew install ${{matrix.otp}} rebar3
  #     - name: Compile
  #       run: rebar3 compile
  #     - name: Run tests
  #       run: rebar3 eunit

  test-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.3
          rebar3-version: 3.17
      - run: |
          Install-Module -Name posh-vs -Force
          Install-PoshVs
          . $profile
      - name: Compile
        run: |
          rebar3 compile
      - name: Run tests
        run: |
          rebar3 eunit
